language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - PLUGIN_NAME=HasNo
    - REQUIRE=""
    - DB=mysql CAKE_VERSION=2.6
    - secure: "TsoeAZwdK27t4D6dImCIqY7viI8hH2EInxHSUCnDt2arw+BFZxU/Cqoxrws6roEAMx67h8MKS6D/bak62TfKzNVYoP3jxU+nSA8sPEJaVZ+UY4iovWqYUK9rDwok84ePIRFiXDIYfa54dT6iwWFUJ3oMlzvGYBGIstse7grUNc4="
    
  matrix:
    - DB=mysql CAKE_VERSION=2.4
    - DB=mysql CAKE_VERSION=2.5
    - DB=mysql CAKE_VERSION=2.6
    - DB=pgsql CAKE_VERSION=2.4
    - DB=pgsql CAKE_VERSION=2.5
    - DB=pgsql CAKE_VERSION=2.6
    
before_script:
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - sh ./before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
