language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - PLUGIN_NAME=HasNo
    - REQUIRE=""
    - DB=mysql CAKE_VERSION=2.7
    - secure: "jph3QWgBhdi+pbNATN/EGxHL0OTzaegkc5pyCG7ZzKcUZtGy+ykLPLJJcNM/rbIK4DqDtq3krqkiCt5ryw+wBnhQW/FdkvQvXC8QDmcXI+woG+ejHj9H/mzO4Fae/CPd/rqm00yDu07AyDO64DZToVhpBExkEc2yLx2i9/deJMY="
    
  matrix:
    - DB=mysql CAKE_VERSION=2.5
    - DB=mysql CAKE_VERSION=2.6
    - DB=mysql CAKE_VERSION=2.7
    - DB=pgsql CAKE_VERSION=2.5
    - DB=pgsql CAKE_VERSION=2.6
    - DB=pgsql CAKE_VERSION=2.7
    
before_script:
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - sh ./before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
